[project]
authors = ["Oliver Batchelor <oliver.batchelor@canterbury.ac.nz>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "example"
platforms = ["linux-64"]
version = "0.1.0"


[pypi-dependencies]
my-package = { path = "./my-package", editable = true }
my-app  = { path = "./my-app", editable = true }

[tasks]

[dependencies]
python = "3.11.*"
